language: node_js
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - PORT=99 node server.js  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
